Logging

diff --git a/cluster/apps/home-monitoring/home-assistant/helm-release.yaml b/cluster/apps/home-monitoring/home-assistant/helm-release.yaml
--- a/cluster/apps/home-monitoring/home-assistant/helm-release.yaml
+++ b/cluster/apps/home-monitoring/home-assistant/helm-release.yaml
@@ -38,14 +38,17 @@ spec:
           - "-c"
           - |
             HA_CONFIG_FILE="/config/configuration.yaml"
-            if ! grep -q "#START_MARKER" "$HA_CONFIG_FILE"
+            if ! ([ -f "$HA_CONFIG_FILE" ] && grep -q "#START_MARKER" "$HA_CONFIG_FILE")
             then
+              echo "File or markers not found, adding them"
               # If not marker not found
               echo "#START_MARKER" >> "$HA_CONFIG_FILE"
               echo "#END_MARKER" >> "$HA_CONFIG_FILE"
             fi
             # Replace the content between the markers with a HA load command
+            echo "Updating config to include init_config directory..."
             sed -ni '/#START_MARKER/{p;:a;N;/#END_MARKER/!ba;s/.*\n/!include_dir_named init_config\/\n/};p' "$HA_CONFIG_FILE"
+            echo "Home-Assistant config updated"
         securityContext:
           runAsUser: 0
     ingress:
